Added default ArgoCD wave 2 for hpa
letsbuilders/jsonnet-libs pull request #69
Opened 2023-06-20 10:26 UTC by YuriiBudnyi

2023-06-21 11:28 UTC, PatTheSilent requested changes

2023-06-21 11:28 UTC, PatTheSilent commented on kubernetes/config-skeleton.libsonnet
> +            'argocd.argoproj.io/sync-wave': '2',
pls fix indentation :)

2023-06-26 07:20 UTC, YuriiBudnyi commented on kubernetes/config-skeleton.libsonnet
> +            'argocd.argoproj.io/sync-wave': '2',
Fixed)

2023-06-28 12:50 UTC, PatTheSilent approved these changes

2023-06-30 07:10 UTC, PatTheSilent approved these changes

2023-06-30 07:15 UTC, merged